# Generated by Django 3.0.14 on 2023-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_subscriberuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberuser',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriberuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
