# Generated by Django 3.0.14 on 2023-03-20 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('birthyear', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=40000)),
                ('photo', models.ImageField(blank=True, upload_to='author/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AuthorInfo',
                'verbose_name_plural': 'AuthorsInfos',
            },
        ),
        migrations.CreateModel(
            name='BlogContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_field', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('context', models.TextField(blank=True, max_length=100000000)),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/thumbnails')),
                ('author', models.ManyToManyField(related_name='authors', to='blog.AuthorInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='blog/Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogContext')),
            ],
            options={
                'verbose_name': 'BlogImage',
                'verbose_name_plural': 'BlogImages',
            },
        ),
        migrations.AddField(
            model_name='blogcontext',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='blogcontext',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blog.Tags'),
        ),
        migrations.CreateModel(
            name='AuthorSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('url', models.CharField(blank=True, max_length=1500)),
                ('alias', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.AuthorInfo')),
            ],
            options={
                'verbose_name': 'AuthorSocial',
                'verbose_name_plural': 'AuthorsSocials',
            },
        ),
    ]
