# Generated by Django 3.0.14 on 2023-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontext',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
