# Generated by Django 3.0.14 on 2023-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, default='images/no-image.png', upload_to='carousel/Images'),
        ),
    ]
