# Generated by Django 3.0.14 on 2023-03-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230329_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, default='carousel/Images/no-image.png', upload_to='carousel/Images'),
        ),
    ]
